Update op21.yml

diff --git a/.github/workflows/op21.yml b/.github/workflows/op21.yml
--- a/.github/workflows/op21.yml
+++ b/.github/workflows/op21.yml
@@ -4,18 +4,34 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-
+  deploy-via-tailscale:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Tailscale
-      uses: tailscale/github-action@v2
-      with:
-        oauth-client-id: $Env:TS_OAUTH_CLIENT_ID
-        oauth-secret: $Env:TS_OAUTH_SECRET
-      env:
-        TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
-        TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
-    - name: test
-      run: htop
+      - name: Check out code
+        uses: actions/checkout@v2
+
+      - name: Debug Secrets
+        run: |
+          echo "Checking TS_OAUTH_CLIENT_ID"
+          if [ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]; then
+            echo "::error::TS_OAUTH_CLIENT_ID is empty"
+            exit 1
+          else
+            echo "TS_OAUTH_CLIENT_ID is set"
+          fi
+          echo "Checking TS_OAUTH_SECRET"
+          if [ -z "${{ secrets.TS_OAUTH_SECRET }}" ]; then
+            echo "::error::TS_OAUTH_SECRET is empty"
+            exit 1
+          else
+            echo "TS_OAUTH_SECRET is set"
+          fi
+
+      - name: Setup Tailscale
+        uses: tailscale/github-action@v2
+        with:
+          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
+          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
+          tags: tag:ci
+      - name: test
+        run: htop
